# 放在 .github/workflows/auto-renew.yml
name: EUserv IPv6 VPS Auto-Renew

on:
  workflow_dispatch:                     # 手动触发
  schedule:
    - cron:  '0 3 * * *'                # 每天 03:00 UTC（对应 CET/CEST 04:00/05:00）运行一次

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests beautifulsoup4

      - name: 运行续费脚本
        env:
          USERNAME: ${{ secrets.USERNAME }}                 # 你的 EUserv 登录名（或邮箱），可多个用空格分隔
          PASSWORD: ${{ secrets.PASSWORD }}                 # 密码，同样可用空格分隔
          MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}  # mailparser.io 下载 ID，按账号顺序空格分隔
          TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}         # （可选）你的 TrueCaptcha 用户 ID
          TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}         # （可选）你的 TrueCaptcha API Key
          RECEIVER_EMAIL: ${{ secrets.NOTIFY_EMAIL }}               # （可选）收邮件通知
          YD_EMAIL: ${{ secrets.YD_EMAIL }}                         # （可选）雅虎邮箱登录
          YD_APP_PWD: ${{ secrets.YD_APP_PWD }}                     # （可选）雅虎授权码
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}                 # （可选）Telegram Bot Token
          TG_USER_ID: ${{ secrets.TG_USER_ID }}                     # （可选）Telegram Chat ID
        run: |
          python3 main.py
