# 放在 .github/workflows/auto-renew.yml
name: EUserv IPv6 VPS Auto-Renew

on:
  workflow_dispatch:                 # 手动触发
  schedule:
    - cron: '0 3 * * *'              # 每天 UTC 03:00（CET/CEST 04:00/05:00）

jobs:
  renew:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install requests beautifulsoup4

      - name: 运行续费脚本
        env:
          USERNAME:                   ${{ secrets.USERNAME }}                     # EUserv 登录名或邮箱
          PASSWORD:                   ${{ secrets.PASSWORD }}                     # EUserv 密码
          MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}   # mailparser.io URL ID
          TRUECAPTCHA_USERID:         ${{ secrets.TRUECAPTCHA_USERID }}           # （可选）TrueCaptcha 用户 ID
          TRUECAPTCHA_APIKEY:         ${{ secrets.TRUECAPTCHA_APIKEY }}           # （可选）TrueCaptcha API Key
          RECEIVER_EMAIL:             ${{ secrets.RECEIVER_EMAIL }}               # （可选）通知用邮箱
          YD_EMAIL:                   ${{ secrets.YD_EMAIL }}                     # （可选）雅虎邮箱
          YD_APP_PWD:                 ${{ secrets.YD_APP_PWD }}                   # （可选）雅虎授权码
          TG_BOT_TOKEN:               ${{ secrets.TG_BOT_TOKEN }}                 # （可选）Telegram Bot Token
          TG_USER_ID:                 ${{ secrets.TG_USER_ID }}                   # （可选）Telegram Chat ID
        run: |
          python3 main.py
