name: Auto Renew EUserv VPS

on:
  schedule:
    - cron: "0 8 * * *"  # 每天 08:00 UTC 运行（北京时间 16:00）
  workflow_dispatch:     # 手动触发

jobs:
  renew:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
      USE_PROXY: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install requests beautifulsoup4 ddddocr

      - name: Run auto renew script
        run: python euserv_auto_renew.py
