name: EUserv Auto-Renew

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run auto-renew script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          OCRSPACE_API_KEY: ${{ secrets.OCR_API_KEY }}
          MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_API_HOST: ${{ secrets.TG_API_HOST }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          YD_EMAIL: ${{ secrets.YD_EMAIL }}
          YD_APP_PWD: ${{ secrets.YD_APP_PWD }}
          PROXIES: ${{ secrets.PROXIES }}
        run: |
          python euserv_auto_renew.py
